server {
  listen 80;
  server_name example.com;

  root /usr/share/nginx/html/main-react-app;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache";
  }

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}

server {
  listen 80;
  server_name static.example.com;

  root /usr/share/nginx/html/static;

  location ~* /.+/index.html$ {
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "no-cache";
  }

  location / {
    add_header Access-Control-Allow-Origin *;
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff2?)$ {
    add_header Access-Control-Allow-Origin *;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
